install:
- pip install --user awscli
- wget https://github.com/gohugoio/hugo/releases/download/v0.56.3/hugo_0.56.3_Linux-64bit.deb
- sudo dpkg -i hugo*.deb
- hugo version
before_script:
- rm -rf public
- hugo
script:
- aws s3 sync public/ s3://1mod --acl public-read --delete
- aws cloudfront create-invalidation --distribution-id EAHK7UH6Y15RH --paths '/*'
branches:
  only:
  - master
